###### 1) Mean speed of all rides

###### 2) Number of rides taken in February

###### 3) Number of rides where tip more than 50

###### 4) Number of rides where drop was JFK

In [1]:
import numpy as np

In [2]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter=',', skip_header=True)

###### Mean speed of all rides

In [16]:
taxi[:,7]

array([21.  , 16.29, 12.7 , ..., 17.48, 12.76, 17.54])

In [17]:
taxi[:,8]

array([2037., 1520., 1462., ..., 2822., 1083., 1711.])

In [3]:
speed = taxi[:,7]/(taxi[:,8]/3600)

In [18]:
speed

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

In [4]:
mean_speed = speed.mean()

In [5]:
print(mean_speed)

32.24258580925573


###### Number of rides taken in February

In [6]:
taxi[:,1]

array([1., 1., 1., ..., 6., 6., 6.])

In [7]:
taxi[:,1]==2

array([False, False, False, ..., False, False, False])

In [8]:
feb_rides = taxi[taxi[:,1]==2,1]

In [9]:
print(feb_rides.shape[0])

13333


###### Number of rides where tip more than 50

In [10]:
taxi[:,12]

array([11.65,  8.  ,  0.  , ...,  5.  ,  8.95,  0.  ])

In [11]:
taxi[:,12]>50

array([False, False, False, ..., False, False, False])

In [12]:
ride_tip_50 = taxi[taxi[:,12]>50,12]

In [13]:
print(ride_tip_50.shape[0])

16


###### Number of rides where drop was JFK

**The drop off code for JFK is 2**

In [14]:
jfk_drop = taxi[taxi[:,6]==2,6]

In [15]:
print(jfk_drop.shape[0])

11832
