In [1]:
import sklearn

In [2]:
import numpy as np

In [3]:
myarr2 = np.array([1,23,13,6])

In [4]:
myarr2

array([ 1, 23, 13,  6])

In [5]:
myarr2 = np.array([1,23,13,6], np.int8)

***np.int8 is given for memory allocation. If our number is bigger we can use np.int16, np.int32, np.int64***

In [6]:
myarr1 = np.array([1,23,13,6], np.int16)

In [7]:
myarr1[0]

1

In [8]:
#myarr1[0,1]

In [9]:
myarr = np.array([[1,23,13,6]], np.int64)

In [10]:
myarr[0,1]

23

In [11]:
myarr.shape

(1, 4)

In [12]:
myarr.dtype

dtype('int64')

In [13]:
myarr[0,1] = 52

In [14]:
myarr

array([[ 1, 52, 13,  6]], dtype=int64)

## Array Creation

### 1)Conversion from other Python structures 
##### (i.e. lists and tuples)

In [15]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
np.array({34,23,23})

array({34, 23}, dtype=object)

<hr>

### 2) Intrinsic NumPy array creation functions
##### (e.g. arange, ones, zeros, etc.)

In [21]:
zeros = np.zeros((2,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros.shape[0]

2

In [102]:
zeros.shape[1]

5

In [103]:
# zeros.shape[3]

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
lspace1 = np.linspace(1,50,10)

In [107]:
lspace1

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [108]:
lspace2 = np.linspace(1,10,10)

In [109]:
lspace2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
lspace = np.linspace(1,5,12)

In [33]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [34]:
ones = np.ones((2,5))

In [35]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
emp = np.empty((4,6))

In [37]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.06810132e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [1.60218220e-306, 1.86921279e-306, 1.69119330e-306,
        9.34611148e-307, 1.60220393e-306, 8.45593934e-307],
       [1.11260687e-306, 1.60217812e-306, 1.11261638e-306,
        9.34605037e-307, 8.34451504e-308, 1.78005909e-306]])

In [38]:
emp_like = np.empty_like(lspace)

In [39]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [40]:
ide = np.identity(45)

In [41]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [42]:
ide.shape

(45, 45)

In [43]:
arr = np.arange(99)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr = arr.reshape(3,33)

In [46]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr = arr.ravel()

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [49]:
arr.shape

(99,)

In [50]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [51]:
ar = np.array(x)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
ar.sum(axis=0)

array([12,  8,  9])

In [54]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [55]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [56]:
ar.flat

In [57]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [58]:
ar.ndim # gives number of dimensions

2

In [59]:
ar.size

9

In [60]:
ar.nbytes #Total bytes consumed

36

In [61]:
one = np.array([1,3,4,634,2])

In [62]:
one.argmax() # Gives index of a large element

3

In [63]:
one.argmin() # Gives index of a smaller element

0

In [64]:
one.argsort() # Gives index numbers of a sorted elements

array([0, 4, 1, 2, 3], dtype=int64)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.argmin()

8

In [67]:
ar.argmax()

6

In [68]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [69]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [70]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [71]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [72]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [73]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [74]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

## Matrix operations

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
ar2 = np.array([[1, 2, 1], [4, 0, 6], [8, 1, 0]])

In [78]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [80]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [81]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [82]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [83]:
ar.sum()

29

In [84]:
ar.min()

0

In [85]:
ar.max()

7

In [86]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [88]:
type(np.where(ar>5))

tuple

In [89]:
np.count_nonzero(ar)

8

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [91]:
ar[1,2] = 0

In [92]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [93]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [94]:
import sys

In [95]:
py_ar = [0,4,55,2]

In [96]:
np_ar = np.array(py_ar)

In [97]:
sys.getsizeof(1)*len(py_ar)

112

In [98]:
np_ar.itemsize*np_ar.size

16

In [99]:
np_ar.tolist()

[0, 4, 55, 2]

In [100]:
new_list = list(range(0,10000000))

In [101]:
sys.getsizeof(new_list)

80000056

In [132]:
data = (np.linspace(1,10,21))*3

In [133]:
newdata = data.reshape(7,3)

In [134]:
newdata

array([[ 3.  ,  4.35,  5.7 ],
       [ 7.05,  8.4 ,  9.75],
       [11.1 , 12.45, 13.8 ],
       [15.15, 16.5 , 17.85],
       [19.2 , 20.55, 21.9 ],
       [23.25, 24.6 , 25.95],
       [27.3 , 28.65, 30.  ]])

In [135]:
np.random.shuffle(newdata)

In [136]:
newdata

array([[ 3.  ,  4.35,  5.7 ],
       [15.15, 16.5 , 17.85],
       [27.3 , 28.65, 30.  ],
       [19.2 , 20.55, 21.9 ],
       [23.25, 24.6 , 25.95],
       [ 7.05,  8.4 ,  9.75],
       [11.1 , 12.45, 13.8 ]])

In [139]:
newdata[2:5]

array([[27.3 , 28.65, 30.  ],
       [19.2 , 20.55, 21.9 ],
       [23.25, 24.6 , 25.95]])