In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data1 = pd.read_csv('train.csv')

In [3]:
data = np.array(data1) #Creating numpy array (Matrics)

In [4]:
data

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [5]:
data.shape[0] #Gives Number of rows

42000

In [6]:
data.shape[1] #Gives number of columns

785

In [7]:
m,n = data.shape

In [8]:
m #Number of rows

42000

In [9]:
n #Number of columns

785

In [10]:
np.random.shuffle(data) # shuffle before splitting into dev and training sets

In [11]:
data

array([[8, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [9, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
data[0:1000] #Selecting rows from index 0 to 1000

array([[8, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
data_dev = data[0:1000].T #Transpose of the array

In [14]:
data_dev.shape

(785, 1000)

In [15]:
data_dev

array([[8, 8, 0, ..., 7, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
Y_dev = data_dev[0] #Gives elements of first row

In [17]:
# Y_dev

In [18]:
X_dev = data_dev[1:n] #Selecting rows from index 1 to n(in this case n=785)

In [19]:
temp1 = X_dev.copy()

In [20]:
np.random.shuffle(temp1)
temp1

array([[  0,   0,   0, ...,   0,   0,   0],
       [253,   0, 255, ...,   0, 249,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0, 254,   0, ...,   0, 248, 254]], dtype=int64)

In [21]:
X_dev = X_dev / 255.

In [22]:
X_dev

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
temp2 = X_dev.copy()

In [24]:
np.random.shuffle(temp2)
temp2

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.76862745, 0.99607843, 0.        , ..., 0.        , 0.99607843,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.14901961,
        0.        ],
       [0.07058824, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [25]:
data_train = data[1000:m].T

In [26]:
data_train.shape

(785, 41000)

In [27]:
data_train

array([[2, 5, 1, ..., 9, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
Y_train = data_train[0]

In [29]:
Y_train.shape

(41000,)

In [30]:
Y_train

array([2, 5, 1, ..., 9, 1, 0], dtype=int64)

In [31]:
X_train = data_train[1:n]

In [32]:
X_train.shape

(784, 41000)

In [33]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
temp3 = X_train.copy()

In [35]:
np.random.shuffle(temp3)
temp3

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [ 42,   0,   0, ...,   0,   0, 227],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [36]:
X_train = X_train / 255.

In [37]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
temp4 = X_train.copy()

In [39]:
np.random.shuffle(temp4)
temp4

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.95294118, 0.        ,
        0.        ],
       [0.        , 0.        , 0.99215686, ..., 0.99607843, 1.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.90588235, 0.42745098, 0.        , ..., 0.        , 0.        ,
        0.65882353],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [40]:
W1 = np.random.rand(10,784)-0.5
b1 = np.random.rand(10,1)-0.5
W2 = np.random.rand(10,10)-0.5
b2 = np.random.rand(10,1)-0.5

In [41]:
Z1 = W1.dot(X_train) + b1

In [42]:
Z1.shape

(10, 41000)

In [43]:
Z1

array([[-1.65460731, -0.30674409, -1.13585934, ..., -2.10707135,
        -1.75109026,  0.84074447],
       [ 1.3234899 ,  1.97622896,  0.90227796, ...,  3.10417054,
         0.4364482 , -0.04789759],
       [ 0.49156846, -0.8708127 ,  2.25093928, ..., -1.03965515,
         1.43485763,  0.49460294],
       ...,
       [-1.63020153, -4.05263776, -1.56453073, ..., -1.46691059,
        -1.07707755,  0.06271161],
       [-2.24079548, -0.08664745,  1.20237221, ...,  1.11076704,
         1.78693339, -0.28550783],
       [-0.72767693, -4.41402894, -0.1508893 , ..., -3.36951844,
         0.41202847, -6.28792247]])

In [44]:
A1 = np.maximum(0,Z1) #ReLU(Rectified Linear Unit) function

In [45]:
A1

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.84074447],
       [1.3234899 , 1.97622896, 0.90227796, ..., 3.10417054, 0.4364482 ,
        0.        ],
       [0.49156846, 0.        , 2.25093928, ..., 0.        , 1.43485763,
        0.49460294],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.06271161],
       [0.        , 0.        , 1.20237221, ..., 1.11076704, 1.78693339,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.41202847,
        0.        ]])

In [46]:
Z2 = W2.dot(A1)+b2

In [47]:
Z2.shape

(10, 41000)

In [48]:
Z2

array([[ 0.51790826, -0.63461724,  2.21562424, ...,  0.08914361,
         1.52240929, -1.6323412 ],
       [-0.08087468,  0.38935935,  2.73023929, ..., -0.77734074,
         1.71598912, -0.46937144],
       [-1.19620583, -3.88312932, -4.39776703, ..., -0.6736374 ,
        -3.8304727 , -4.17212843],
       ...,
       [-0.30940346,  0.291919  , -0.15879386, ...,  0.13913275,
        -0.64797287, -2.27028267],
       [-0.06839033, -1.27713751, -0.63776512, ...,  0.51263134,
        -1.26049798, -1.77836293],
       [-0.13003134,  0.74921667, -0.01797305, ..., -0.17134414,
         0.22824476,  0.89356995]])

In [49]:
A2 = np.exp(Z2)/sum(np.exp(Z2)) #Softmax function

In [50]:
A2.shape

(10, 41000)

In [51]:
A2

array([[8.88018703e-02, 4.31250387e-03, 1.02475207e-01, ...,
        5.06853991e-02, 9.02434757e-02, 1.98329301e-03],
       [4.87948498e-02, 1.20070656e-02, 1.71440443e-01, ...,
        2.13095117e-02, 1.09518242e-01, 6.34538869e-03],
       [1.59952791e-02, 1.67462907e-04, 1.37549644e-04, ...,
        2.36380305e-02, 4.27256524e-04, 1.56448465e-04],
       ...,
       [3.88262278e-02, 1.08922870e-02, 9.53722716e-03, ...,
        5.32835166e-02, 1.02998480e-02, 1.04793035e-03],
       [4.94078407e-02, 2.26822687e-03, 5.90755200e-03, ...,
        7.74107463e-02, 5.58231758e-03, 1.71384070e-03],
       [4.64542575e-02, 1.72076249e-02, 1.09794309e-02, ...,
        3.90620002e-02, 2.47381547e-02, 2.47956877e-02]])

In [52]:
Y_train

array([2, 5, 1, ..., 9, 1, 0], dtype=int64)

In [53]:
Y_train.size

41000

In [54]:
Y_train.max()

9

In [55]:
one_hot_Y = np.zeros((Y_train.size, Y_train.max() + 1))

In [56]:
one_hot_Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
one_hot_Y.shape

(41000, 10)

In [58]:
np.arange(Y_train.size)

array([    0,     1,     2, ..., 40997, 40998, 40999])

In [59]:
one_hot_Y[np.arange(Y_train.size), Y_train] = 1

In [60]:
one_hot_Y[0,1]

0.0

In [61]:
one_hot_Y[1,3]

0.0

In [62]:
one_hot_Y[2,5]

0.0

In [63]:
one_hot_Y[2,0]

0.0

In [64]:
one_hot_Y = one_hot_Y.T

In [65]:
one_hot_Y

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [66]:
A2.shape

(10, 41000)

In [67]:
one_hot_Y.shape

(10, 41000)

In [68]:
dZ2 = A2-one_hot_Y

In [69]:
dZ2

array([[ 8.88018703e-02,  4.31250387e-03,  1.02475207e-01, ...,
         5.06853991e-02,  9.02434757e-02, -9.98016707e-01],
       [ 4.87948498e-02,  1.20070656e-02, -8.28559557e-01, ...,
         2.13095117e-02, -8.90481758e-01,  6.34538869e-03],
       [-9.84004721e-01,  1.67462907e-04,  1.37549644e-04, ...,
         2.36380305e-02,  4.27256524e-04,  1.56448465e-04],
       ...,
       [ 3.88262278e-02,  1.08922870e-02,  9.53722716e-03, ...,
         5.32835166e-02,  1.02998480e-02,  1.04793035e-03],
       [ 4.94078407e-02,  2.26822687e-03,  5.90755200e-03, ...,
         7.74107463e-02,  5.58231758e-03,  1.71384070e-03],
       [ 4.64542575e-02,  1.72076249e-02,  1.09794309e-02, ...,
        -9.60938000e-01,  2.47381547e-02,  2.47956877e-02]])

In [70]:
dZ2.shape

(10, 41000)

In [71]:
A1.shape

(10, 41000)

In [72]:
dW2 = 1 / m * dZ2.dot(A1.T)

In [73]:
dW2.shape

(10, 10)

In [74]:
dW2

array([[ 6.10014544e-04, -1.92127927e-01,  4.14199362e-03,
         2.44878053e-03,  5.12147481e-03, -9.77956068e-02,
        -3.63027255e-01, -3.87819587e-03, -1.81727259e-02,
         5.47842309e-03],
       [ 7.22309576e-03, -2.69118092e-02, -4.75343113e-02,
        -2.19497386e-02, -2.89507852e-01, -3.29620122e-02,
        -1.33812956e-01,  1.54604825e-03, -9.18305006e-02,
        -2.46387657e-02],
       [-5.53879655e-03, -2.24094825e-01, -5.73741984e-02,
        -2.31370356e-03, -3.25582119e-01, -8.86769945e-02,
        -4.62238757e-01,  5.76432244e-05, -1.52597329e-01,
        -6.74519111e-03],
       [ 1.04579748e-01,  1.28153932e+00,  2.07381347e-01,
         1.93026528e-02,  1.39092710e+00,  7.46299014e-01,
         2.11013032e+00,  1.34754056e-02,  4.04645900e-01,
         3.96412209e-02],
       [-7.81543929e-02, -1.68055802e-01, -2.14554631e-02,
        -1.03038492e-03, -1.37527340e-01, -1.38332900e-01,
        -2.94334443e-01, -9.82806757e-04, -1.14907405e-02,
        -1.

In [75]:
db2 = 1 / m * np.sum(dZ2)

In [76]:
db2

-6.606355674150455e-17

In [77]:
def ReLU_deriv(Z):
    return Z > 0

In [78]:
dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)

In [79]:
dZ1

array([[-0.        , -0.        , -0.        , ...,  0.        ,
        -0.        ,  0.36136599],
       [-0.11892413,  0.58817174,  0.49475218, ...,  0.61087913,
         0.4651599 ,  0.        ],
       [ 0.34841475, -0.        , -0.20796472, ...,  0.        ,
        -0.20026411, -0.19322343],
       ...,
       [ 0.        ,  0.        , -0.        , ..., -0.        ,
        -0.        ,  0.75808884],
       [ 0.        , -0.        , -0.19803877, ..., -0.0914235 ,
        -0.18099744, -0.        ],
       [-0.        ,  0.        ,  0.        , ...,  0.        ,
         0.58553226,  0.        ]])

In [80]:
dZ1.shape

(10, 41000)

In [81]:
X_train.shape

(784, 41000)

In [82]:
dW1 = 1 / m * dZ1.dot(X_train.T)

In [83]:
dW1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [84]:
db1 = 1 / m * np.sum(dZ1)

In [85]:
db1

0.8223640795484723

In [86]:
A2

array([[8.88018703e-02, 4.31250387e-03, 1.02475207e-01, ...,
        5.06853991e-02, 9.02434757e-02, 1.98329301e-03],
       [4.87948498e-02, 1.20070656e-02, 1.71440443e-01, ...,
        2.13095117e-02, 1.09518242e-01, 6.34538869e-03],
       [1.59952791e-02, 1.67462907e-04, 1.37549644e-04, ...,
        2.36380305e-02, 4.27256524e-04, 1.56448465e-04],
       ...,
       [3.88262278e-02, 1.08922870e-02, 9.53722716e-03, ...,
        5.32835166e-02, 1.02998480e-02, 1.04793035e-03],
       [4.94078407e-02, 2.26822687e-03, 5.90755200e-03, ...,
        7.74107463e-02, 5.58231758e-03, 1.71384070e-03],
       [4.64542575e-02, 1.72076249e-02, 1.09794309e-02, ...,
        3.90620002e-02, 2.47381547e-02, 2.47956877e-02]])

In [87]:
A2.shape

(10, 41000)

In [88]:
A2[0][0]

0.08880187027129113

In [89]:
for i in range(len(A2)):
    print(A2[i][200])

0.0638283220250073
0.07689032472703657
0.05148052663264752
0.14608412123621942
0.039366751028650344
0.1835772140363233
0.17284578768940023
0.04539135675103694
0.05683956589652176
0.1636960299771564


In [90]:
temp9 = np.argmax(A2,0)

In [91]:
temp9

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [92]:
temp9.shape

(41000,)

In [169]:
tlist = []
for i in range(len(A2)):
    tlist.append(np.sum(A2[i][:]))

In [170]:
tlist

[2106.682688651104,
 2651.7541504112255,
 402.95951995256877,
 24329.3688174205,
 301.319837975624,
 2687.1737459267865,
 4309.934768104813,
 1261.7781450102277,
 1199.5386315789292,
 1749.4896949682177]

In [298]:
np.sum(temp9==Y_train) #Compares element by element and returns count of matching elements.

3962

In [299]:
Y_train.size

41000

In [300]:
temp13 = np.sum(temp9==Y_train)

In [301]:
accuracy = temp13/Y_train.size

In [302]:
accuracy

0.09663414634146342

<hr>
<hr>

In [93]:
temp7 = ReLU_deriv(Z1)

In [94]:
temp7.shape

(10, 41000)

In [95]:
temp7

array([[False, False, False, ..., False, False,  True],
       [ True,  True,  True, ...,  True,  True, False],
       [ True, False,  True, ..., False,  True,  True],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ...,  True,  True, False],
       [False, False, False, ..., False,  True, False]])

In [96]:
temp8 = W2.T.dot(dZ2)

In [97]:
temp8

array([[-0.14845681, -0.20809215, -0.25037563, ...,  0.38597374,
        -0.25663368,  0.36136599],
       [-0.11892413,  0.58817174,  0.49475218, ...,  0.61087913,
         0.4651599 ,  0.13833334],
       [ 0.34841475, -0.33790368, -0.20796472, ...,  0.13602369,
        -0.20026411, -0.19322343],
       ...,
       [ 0.10610844,  0.44969818, -0.04657252, ..., -0.12924022,
        -0.09117092,  0.75808884],
       [ 0.42232186, -0.2888187 , -0.19803877, ..., -0.0914235 ,
        -0.18099744, -0.15562857],
       [-0.14781632,  0.05668783,  0.55545287, ...,  0.55551064,
         0.58553226,  0.09276137]])

In [98]:
2*True

2

In [99]:
2*False

0

<hr>
<hr>

In [100]:
tdZ2 = dZ2.copy()

In [101]:
# sum(tdZ2)

In [102]:
np.sum(tdZ2)

-2.7746693831431912e-12

<hr>
<hr>

In [103]:
zeros = np.zeros((10,5))

In [104]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
zeros.shape

(10, 5)

In [106]:
zeros.size

50

In [107]:
ttrain = np.array([4,1,2,0,3,4,3,0,1,4])

In [108]:
ttrain

array([4, 1, 2, 0, 3, 4, 3, 0, 1, 4])

In [109]:
ttrain.size

10

In [110]:
t1train = np.arange(ttrain.size)

In [111]:
t1train

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
zeros[t1train,ttrain] = 1

In [113]:
zeros

array([[0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

<hr>
<hr>

In [114]:
tZ2 = Z2.copy()

In [115]:
temp5 = np.exp(tZ2)

In [116]:
temp5.shape

(10, 41000)

In [117]:
temp5

array([[1.67851296e+00, 5.30138365e-01, 9.16712979e+00, ...,
        1.09323764e+00, 4.58325430e+00, 1.95471399e-01],
       [9.22309264e-01, 1.47603487e+00, 1.53365564e+01, ...,
        4.59626654e-01, 5.56217443e+00, 6.25395241e-01],
       [3.02339164e-01, 2.05863031e-02, 1.23047855e-02, ...,
        5.09850671e-01, 2.16993559e-02, 1.54194061e-02],
       ...,
       [7.33884616e-01, 1.33899456e+00, 8.53172214e-01, ...,
        1.14927666e+00, 5.23105103e-01, 1.03282980e-01],
       [9.33895879e-01, 2.78834320e-01, 5.28472179e-01, ...,
        1.66967891e+00, 2.83512806e-01, 1.68914446e-01],
       [8.78067915e-01, 2.11534236e+00, 9.82187504e-01, ...,
        8.42531572e-01, 1.25639281e+00, 2.44383848e+00]])

In [118]:
temp6 = sum(np.exp(tZ2))

In [119]:
temp6.shape

(41000,)

In [120]:
temp6

array([ 18.90177484, 122.93052516,  89.4570507 , ...,  21.56908425,
        50.78765266,  98.55901204])

In [121]:
temp5/temp6

array([[8.88018703e-02, 4.31250387e-03, 1.02475207e-01, ...,
        5.06853991e-02, 9.02434757e-02, 1.98329301e-03],
       [4.87948498e-02, 1.20070656e-02, 1.71440443e-01, ...,
        2.13095117e-02, 1.09518242e-01, 6.34538869e-03],
       [1.59952791e-02, 1.67462907e-04, 1.37549644e-04, ...,
        2.36380305e-02, 4.27256524e-04, 1.56448465e-04],
       ...,
       [3.88262278e-02, 1.08922870e-02, 9.53722716e-03, ...,
        5.32835166e-02, 1.02998480e-02, 1.04793035e-03],
       [4.94078407e-02, 2.26822687e-03, 5.90755200e-03, ...,
        7.74107463e-02, 5.58231758e-03, 1.71384070e-03],
       [4.64542575e-02, 1.72076249e-02, 1.09794309e-02, ...,
        3.90620002e-02, 2.47381547e-02, 2.47956877e-02]])

<hr>
<hr>

In [122]:
tW1 = np.random.rand(10,5)-0.5

In [123]:
tW1

array([[-0.19761123,  0.23989854, -0.25572329,  0.13558898,  0.27553099],
       [ 0.22281535,  0.29656624, -0.08360195, -0.34921463,  0.22356785],
       [ 0.16802313,  0.4403128 ,  0.33988964,  0.21220064,  0.43793211],
       [-0.19208863, -0.04119497,  0.35146806, -0.22564871, -0.00344075],
       [-0.4311577 ,  0.0450936 ,  0.05651832,  0.19953532, -0.1792506 ],
       [ 0.13119952, -0.0735827 ,  0.03416845, -0.36379341,  0.33502832],
       [-0.04502242, -0.39581782,  0.40964029,  0.1135006 , -0.06864803],
       [ 0.24737163,  0.46090124,  0.4527692 ,  0.3906826 ,  0.29616876],
       [ 0.38027036, -0.06355278,  0.21335469,  0.48758519, -0.30614924],
       [-0.23164411,  0.42251461,  0.23341109, -0.38813942,  0.34420371]])

In [124]:
tb1 = np.random.rand(10,1)-0.5

In [125]:
tb1

array([[-0.21787414],
       [-0.36089516],
       [ 0.26315027],
       [ 0.38100004],
       [-0.18446984],
       [ 0.02194281],
       [-0.42546841],
       [ 0.40463841],
       [ 0.25133125],
       [-0.07075438]])

In [126]:
t2W1 = np.random.randn(10,5)
t1W1 = np.random.rand(10,5)

In [127]:
t2W1

array([[-0.86743454, -0.90078438,  1.50918107, -0.14730819,  0.72832381],
       [ 0.47116374,  1.34021161, -0.27399239, -0.00365216, -0.95583172],
       [ 0.34327212,  0.50443968, -0.19779227, -0.92380488,  1.89817057],
       [-0.79267975,  0.29797388, -1.22237872,  0.22260997, -1.0394518 ],
       [ 0.65651654, -0.05461522, -0.41572962, -0.26876389, -0.88109403],
       [ 0.20269428,  0.33536181, -0.50856693, -1.10173876,  1.21491654],
       [-1.12577335,  0.88443832,  0.00537618,  1.95572359, -1.49911015],
       [-0.635863  , -0.66513929,  0.70723683,  0.7356705 ,  0.71921884],
       [-0.3805867 , -0.33261773, -0.58435465, -0.7454669 , -0.49377857],
       [ 0.34640427,  0.79754213, -0.77526423,  0.14290811,  1.3688261 ]])

In [128]:
t1W1

array([[0.32515308, 0.48045378, 0.14017543, 0.99513981, 0.80157342],
       [0.10556542, 0.04471852, 0.88595365, 0.65703076, 0.56974035],
       [0.66976084, 0.8036093 , 0.44731409, 0.9872475 , 0.17369682],
       [0.26746212, 0.243559  , 0.39123342, 0.87866981, 0.02596544],
       [0.90450345, 0.05895531, 0.25473501, 0.94484297, 0.02194453],
       [0.24668377, 0.75159202, 0.42654469, 0.30444931, 0.74337076],
       [0.69851588, 0.04638037, 0.75775512, 0.19257951, 0.75824735],
       [0.07004821, 0.65042573, 0.10253873, 0.77566007, 0.50006772],
       [0.99012739, 0.67556689, 0.08699092, 0.62747852, 0.3278424 ],
       [0.50141793, 0.17571278, 0.79081365, 0.25543766, 0.7870042 ]])

In [129]:
np.random.randn()

0.45689843656900103

In [130]:
np.random.rand()

0.3014270756718652

<hr>
<hr>

In [131]:
tdata = (np.linspace(0,1,21))

In [132]:
newdata = tdata.reshape(7,3)

In [133]:
newdata

array([[0.  , 0.05, 0.1 ],
       [0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 ],
       [0.45, 0.5 , 0.55],
       [0.6 , 0.65, 0.7 ],
       [0.75, 0.8 , 0.85],
       [0.9 , 0.95, 1.  ]])

In [134]:
newdata/255.

array([[0.        , 0.00019608, 0.00039216],
       [0.00058824, 0.00078431, 0.00098039],
       [0.00117647, 0.00137255, 0.00156863],
       [0.00176471, 0.00196078, 0.00215686],
       [0.00235294, 0.00254902, 0.0027451 ],
       [0.00294118, 0.00313725, 0.00333333],
       [0.00352941, 0.00372549, 0.00392157]])

In [135]:
t3W2 = np.random.rand(10, 10) - 0.5

In [136]:
t3W1 = np.random.rand(10, 784) - 0.5

In [137]:
a = np.array([[1,2],[3,4],[5,8]]) 
b = np.array([[11,12,10],[13,14,15]])

In [138]:
a

array([[1, 2],
       [3, 4],
       [5, 8]])

In [139]:
a.shape

(3, 2)

In [140]:
b

array([[11, 12, 10],
       [13, 14, 15]])

In [141]:
b.shape

(2, 3)

In [142]:
c = np.dot(a,b)

In [143]:
d = a.dot(b)

In [144]:
c

array([[ 37,  40,  40],
       [ 85,  92,  90],
       [159, 172, 170]])

In [145]:
d

array([[ 37,  40,  40],
       [ 85,  92,  90],
       [159, 172, 170]])

In [146]:
c.shape

(3, 3)

In [147]:
d.shape

(3, 3)

In [148]:
np.exp(d)

array([[1.17191424e+16, 2.35385267e+17, 2.35385267e+17],
       [8.22301271e+36, 9.01762841e+39, 1.22040329e+39],
       [1.12933457e+69, 4.99632738e+74, 6.76179381e+73]])

In [149]:
sum(np.exp(d))

array([1.12933457e+69, 4.99632738e+74, 6.76179381e+73])

In [150]:
def matrix_cofactor(matrix):
 
    try:
        determinant = np.linalg.det(matrix)
        if(determinant!=0):
            cofactor = None
            cofactor = np.linalg.inv(matrix).T * determinant
            # return cofactor matrix of the given matrix
            return cofactor
        else:
            raise Exception("singular matrix")
    except Exception as e:
        print("could not find cofactor matrix due to",e)

In [151]:
e = np.array([[2,3,1],[0,5,6],[1,1,2]])
f = np.array([[2,1,-1],[1,0,-1],[1,1,2]])

In [152]:
e

array([[2, 3, 1],
       [0, 5, 6],
       [1, 1, 2]])

In [153]:
f

array([[ 2,  1, -1],
       [ 1,  0, -1],
       [ 1,  1,  2]])

In [154]:
inverse_f = np.linalg.inv(f)

In [155]:
inverse_f

array([[-0.5,  1.5,  0.5],
       [ 1.5, -2.5, -0.5],
       [-0.5,  0.5,  0.5]])

In [156]:
cof_f = matrix_cofactor(f)

In [157]:
cof_f

array([[ 1., -3.,  1.],
       [-3.,  5., -1.],
       [-1.,  1., -1.]])

In [158]:
def matrix_division(m1,m2):
    return np.dot(m1,(np.linalg.inv(m2)))

In [159]:
matrix_division(e,f)

array([[ 3. , -4. ,  0. ],
       [ 4.5, -9.5,  0.5],
       [ 0. ,  0. ,  1. ]])

<hr>
<hr>

In [160]:
temp10 = (np.linspace(1,50,50)).reshape(10,5)

In [161]:
temp10.size

50

In [162]:
temp10

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45.],
       [46., 47., 48., 49., 50.]])

In [163]:
np.random.shuffle(temp10)

In [164]:
temp10

array([[31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [46., 47., 48., 49., 50.],
       [41., 42., 43., 44., 45.],
       [26., 27., 28., 29., 30.],
       [16., 17., 18., 19., 20.],
       [11., 12., 13., 14., 15.],
       [ 1.,  2.,  3.,  4.,  5.],
       [21., 22., 23., 24., 25.],
       [ 6.,  7.,  8.,  9., 10.]])

In [165]:
temp10[9][0] # temp10[index_of_rows][index_of_columns]

6.0

In [166]:
np.argmax(temp10,0) # axis=0 represents columns and axis=1 represents rows

array([2, 2, 2, 2, 2], dtype=int64)

In [178]:
temp10[:,3]

array([34., 39., 49., 44., 29., 19., 14.,  4., 24.,  9.])

In [179]:
temp10[5,:]

array([16., 17., 18., 19., 20.])

In [293]:
temp11 = np.around(np.random.rand(6, 6)*10,decimals=0)
temp12 = np.around(np.random.rand(6, 6)*10,decimals=0)

In [294]:
temp11

array([[ 5., 10.,  8.,  9.,  3.,  5.],
       [ 7.,  8.,  7.,  8.,  5.,  6.],
       [ 7.,  4.,  4.,  1.,  5.,  4.],
       [ 0.,  9., 10.,  5.,  4.,  2.],
       [ 8.,  9.,  7.,  2.,  3.,  8.],
       [ 7.,  5.,  2.,  7.,  0.,  1.]])

In [295]:
temp12

array([[ 4.,  5.,  9.,  3.,  8.,  6.],
       [ 4.,  6.,  4.,  8.,  2.,  5.],
       [ 9., 10.,  2.,  5.,  1.,  8.],
       [ 1.,  5.,  1.,  8.,  3.,  3.],
       [ 9.,  9.,  5.,  9.,  5.,  9.],
       [ 3.,  7.,  3.,  3.,  6.,  4.]])

In [297]:
np.sum(temp11==temp12) #Returns the count of matching elements.

2